create table if not exists product
(
    id bigint generated by default as identity
        constraint product_pkey
            primary key,
    article_number bigint not null
        constraint uk_ci0oroletqpsn3jcj6s3tul9k
            unique,
    description varchar(1000),
    product_name varchar(255) not null,
    price numeric(19,2) not null,
    type varchar(30) not null
);
alter table product owner to postgres;

create table if not exists store
(
    id bigint generated by default as identity
        constraint store_pkey
            primary key,
    address varchar(255) not null,
    name varchar(20) not null
);
alter table store owner to postgres;

create table if not exists product_count
(
    id bigint generated by default as identity
        constraint product_count_pkey
            primary key,
    product_id bigint not null references product(id),
    quantity integer not null,
    store_id bigint not null references store(id)
);
alter table product_count owner to postgres;