create table client
(
    id bigint generated by default as identity
        constraint client_pkey
            primary key,
    birthday_date date not null,
    created_date date,
    email varchar(255) not null,
    first_name varchar(20) not null,
    last_name varchar(30) not null,
    middle_name varchar(30),
    phone_num varchar(20) not null
);
alter table client owner to postgres;

create table store
(
    id bigint generated by default as identity
        constraint store_pkey
            primary key,
    address varchar(255) not null,
    name varchar(20) not null
);
alter table store owner to postgres;

create table orders
(
    id bigint generated by default as identity
        constraint orders_pkey
            primary key,
    is_archive boolean,
    client_id bigint not null references client(id),
    created_time timestamp not null,
    delivery_to bigint,
    is_payment boolean,
    store_id bigint not null references store(id)
);
alter table orders owner to postgres;

create table order_items
(
    id bigint generated by default as identity
        constraint order_items_pkey
            primary key,
    order_id bigint not null references orders(id),
    price numeric(19,2) not null,
    product_id bigint not null,
    product_name varchar(255) not null,
    quantity integer not null,
    store_id bigint references store(id)
);
alter table order_items owner to postgres;

create table basket_unit
(
    id bigint generated by default as identity
        constraint basket_unit_pkey
            primary key,
    client_id bigint not null references client(id),
    product_id bigint not null,
    product_name varchar(255) not null,
    price numeric(19,2) not null,
    quantity_buy integer not null
);
alter table basket_unit owner to postgres;

create table product_count
(
    id bigint generated by default as identity
        constraint product_count_pkey
            primary key,
    number_interested integer,
    product_id bigint not null,
    quantity_stock integer not null,
    store_id bigint not null references store(id)
);
alter table product_count owner to postgres;


